{% set name = "pygments" %}
{% set version = "2.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pygments-{{ version }}.tar.gz
  sha256: 8ace4d3c1dd481894b2005f560ead0f9f19ee64fe983366be1a21e171d12775c

build:
  entry_points:
    - pygmentize = pygments.cmdline:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61
    - pip
  run:
    - python >=3.7

test:
  imports:
    - pygments.styles
    - pygments
    - pygments.lexers
    - pygments.filters
    - pygments.formatters
    - pygments.plugin
  commands:
    - pip check
    - pygmentize -h
  requires:
    - pip


about:
  home: http://pygments.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting, forums, wikis or other applications that need to prettify source code.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - scopatz
